version: '3.8'

services:
  service1:
    image: deividgp/sigma-user-service:latest
    container_name: sigma-user-service
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mongodb

  service2:
    image: deividgp/sigma-security-service:latest
    container_name: sigma-security-service
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mongodb

  service3:
    image: deividgp/sigma-server-service:latest
    container_name: sigma-server-service
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
